### ISSUE TITLE
Same comment as issue filed on gin-gomonitor

### ISSUE THREAD

**Issue by LappleApple** [zalando-techmonkeys/gin-oauth2#13]
[See](https://github.com/zalando-techmonkeys/gin-gomonitor/issues/4).

**Comment by szuecs** [comment]
Thanks, that would be awesome.
We had also one PR that made a lot of sense.

**Comment by LappleApple** [comment]
great -- I don't see the PR but set that info aside and we'll add to the docs. Let me know when you're ready to chat.
