### ISSUE TITLE
Remove AccessTuple from the API

### ISSUE THREAD

**Issue by dolmen** [zalando-techmonkeys/gin-oauth2#4]
The `AccessTuple` type limits the API to a token database being stored in a single process, in memory.

However, this limit could easily be removed if the `AccessTuple` was removed from the API. The `ginoauth2.Auth` function only needs an `accessCheckFunction` closure that will authenticate users, and it should be left to that closure to decide the data source to use.

Here is how to fix the API:
- create a new package `exampleauth` that will only be an example of an authenticator
- move type `AccessTuple` and func `UidCheck` to `exampleauth`
- remove `AccessTuple` from the `ginoauth2.Auth` func signature
- refactor examples to use `func(tc * TokenContainer, ctx *gin.Context) bool { return exampleauth.UidCheck(tc, USERS, ctx) }` where `ginoauth2.UidCheck` was previously used

Tell me if you want a PR that implements this.

**Comment by szuecs** [comment]
Hi!

This is really nice suggestion. 
Of course we would like to get a PR that implements it!

Thanks, sandor
